# Update these handles when you're ready to accept funding.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [your-username]
# patreon: your-handle
# open_collective: your-project
# ko_fi: your-handle
# tidelift: npm/your-package
# buy_me_a_coffee: your-handle
custom: ["https://your-portfolio.com/support"]
